services:
    LupaSearch\Factories\HttpClientFactory:
        class: LupaSearch\Factories\HttpClientFactory
        
    LupaSearch\Factories\HttpClientFactoryInterface: '@LupaSearch\Factories\HttpClientFactory'
        
